# Generated by Django 3.1.1 on 2020-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.CharField(default='example@example.com', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='Secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
