# Generated by Django 3.1.1 on 2020-10-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201002_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Secret',
            field=models.CharField(max_length=64),
        ),
    ]
