# Generated by Django 3.1.1 on 2020-10-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201002_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
