# Generated by Django 3.1.1 on 2020-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_relationsships_type_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='Passhash',
            field=models.CharField(default='asd', max_length=64),
        ),
    ]
