# Generated by Django 3.1.1 on 2020-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_userlogin_passhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='Passhash',
            field=models.CharField(max_length=64),
        ),
    ]
