# Generated by Django 3.1.1 on 2020-10-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20201002_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnonymityCode', models.CharField(max_length=64)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('ActionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.action')),
            ],
        ),
    ]
