# Generated by Django 3.1.1 on 2020-10-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_action_researchdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='id',
        ),
        migrations.RemoveField(
            model_name='relationsships',
            name='id',
        ),
        migrations.RemoveField(
            model_name='researchdata',
            name='id',
        ),
        migrations.AddField(
            model_name='action',
            name='ActionId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='relationsships',
            name='RelationsshipsId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='researchdata',
            name='ResearchDataId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
