# Generated by Django 3.1.1 on 2020-10-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20201002_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationsships',
            name='TypeId',
        ),
        migrations.RemoveField(
            model_name='relationsships',
            name='UserA',
        ),
        migrations.RemoveField(
            model_name='relationsships',
            name='UserB',
        ),
        migrations.RemoveField(
            model_name='researchdata',
            name='ActionId',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='UserId',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Relationsships',
        ),
        migrations.DeleteModel(
            name='ResearchData',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
