# Generated by Django 3.1.1 on 2020-10-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0016_auto_20201002_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('ActionId', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('TypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('FirstName', models.CharField(max_length=64)),
                ('LastName', models.CharField(max_length=64)),
                ('DateOfBirth', models.DateField()),
                ('Email', models.CharField(max_length=64)),
                ('Secret', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passhash', models.CharField(max_length=64)),
                ('UserId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchData',
            fields=[
                ('ResearchDataId', models.IntegerField(primary_key=True, serialize=False)),
                ('AnonymityCode', models.CharField(max_length=64)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('ActionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.action')),
            ],
        ),
        migrations.CreateModel(
            name='Relationsships',
            fields=[
                ('RelationsshipsId', models.IntegerField(primary_key=True, serialize=False)),
                ('TypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.type')),
                ('UserA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserA', to='login.user')),
                ('UserB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserB', to='login.user')),
            ],
        ),
    ]
