"""
Django settings for twelvesteps project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/

Addeb by Kevin
Deployment checklist django site
https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
"""
Added by Kevin
For security reasons we place the secret key in a file wich is not reachable
from the web on deployment server. During local development we will have it
readable for everyone.

Change to a new SECRET_KEY on deployment server
"""

with open('/home/kevin/Projekt/env/Secproject1/conf/secret_key') as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['12steps.kengstrom.se']


# Application definition

INSTALLED_APPS = [
    'breathe.apps.BreatheConfig',
    'call.apps.CallConfig',
    'chat.apps.ChatConfig',
    'check.apps.CheckConfig',
    'home.apps.HomeConfig',
    'danger.apps.DangerConfig',
    'info.apps.InfoConfig',
    'login.apps.LoginConfig',
    'practice.apps.PracticeConfig',
    'prepare.apps.PrepareConfig',
    'savemeplan.apps.SavemeplanConfig',
    'science.apps.ScienceConfig',
    'professionals.apps.ProfessionalsConfig',
    'userprofile.apps.UserprofileConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'twelvesteps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'twelvesteps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
"""
Added by Kevin
read_default_file is the file wich will contain information about the
database. Change /path/to/my.cnf to your .cnf file
This is how the .cnf file should look like
"""

"""
[client]
database = NAME
user = USER
password = PASSWORD
default-character-set = utf8
"""

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'OPTIONS': {
            'autocommit': True,
            'read_default_file': "/home/kevin/Projekt/env/Secproject1/conf/db.cnf",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Stockholm'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = '/var/www/12steps/static/'

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static/',
]

#DEFAULT_FILE_STORAGE = "FileSystemStorage"

MEDIA_ROOT = "/var/www/12steps/media/"
MEDIA_URL = '/media/'

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
